vim.cmd('colorscheme catppuccin')

-- vim.api.nvim_set_hl(0, 'Normal', { bg = 'NONE' })
-- vim.api.nvim_set_hl(0, 'NormalNC', { bg = 'NONE' })
vim.api.nvim_set_hl(0, '@variable', { fg = '#cdd6f4' })
vim.api.nvim_set_hl(0, '@variable.parameter', { fg = '#f38ba8' })
vim.api.nvim_set_hl(0, '@variable.member', { fg = '#b4befe' })
vim.api.nvim_set_hl(0, '@module',           { fg = '#b4befe', italic = true })
vim.api.nvim_set_hl(0, '@type.builtin',     { fg = '#f9e2af', italic = true })
vim.api.nvim_set_hl(0, '@property',         { fg = '#b4befe' })
vim.api.nvim_set_hl(0, '@constructor',      { fg = '#74c7ec' })
vim.api.nvim_set_hl(0, '@keyword.operator', { link = 'Operator' })
vim.api.nvim_set_hl(0, '@keyword.export',   { fg = '#89dceb' })
vim.api.nvim_set_hl(0, '@tag',              { fg = '#cba6f7' })
vim.api.nvim_set_hl(0, '@tag.builtin',      { fg = '#cba6f7' })
vim.api.nvim_set_hl(0, '@tag.attribute',    { fg = '#94e2d5', italic = true })
vim.api.nvim_set_hl(0, '@tag.delimiter',    { fg = '#89dceb' })
